website/music/urls.py
from django.conf.urls import url
from . import views

app_name = "music"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    # /music/<album_id>/
    url(r"^(?P<album_id>[0-9]+)/$", views.details, name="details"),
    # /music/<album_id>/favorite/
    url(r"^(?P<album_id>[0-9]+)/favorite/$", views.favorite, name="favorite")
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r"^music/", include('music.urls'))
]

website/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo= models.CharField(max_length=100)
    def __str__(self):
        return self.album_title + " - " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

website/music/views.py
from django.http import HttpResponse, Http404
from .models import Album
from django.template import loader
from django.shortcuts import render, get_object_or_404

# Create your views here.
def index(request):
    all_obj = Album.objects.all()
    template = loader.get_template("music/index.html")
    cotext = {
        "all_alb" : all_obj
    }
    return HttpResponse(template.render(cotext, request))
    # return render(request, 'music/index.html', cotext)


def details(request, album_id):
    alu = get_object_or_404(Album, pk = album_id)
    return render(request, "music/details.html", {"alb": alu})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk = album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST["song"])
    except (KeyError, Song.DoesNotExist):
        return render(request, "music/details.html",
        {"alb": album,
        'error_message': "You didn't"        
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, "music/details.html", {"alb": album})

website/music/templates/music/details.html
<!-- {{ alb.artist}} - {{alb.album_title }} -->
<!-- {{alb}} -->
<img src={{alb.album_logo}} >
<h2> {{alb.album_title}} </h2>
<h3> {{alb.artist}} </h3>
<!-- 
<ul>{%for song in alb.song_set.all %}
    <li>
        {{song.song_title}} - {{song.file_type}}
    </li>
    {%endfor%}
</ul> -->

{% if error_message %}
<p>
    <strong>
        {{ error_message }}
    </strong>
</p>
{% endif %}

<!-- #action what url you want to sned  this data to -->
<form action="{% url 'music:favorite' alb.id %}" method="POST">
    {% csrf_token %}
    {% for song in alb.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" / >
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                 <img src="https://cdn1.iconfinder.com/data/icons/mini-solid-icons-vol-13/16/629-512.png" style="width:16px;height:16px;">
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Submit!" >
</form>

website/music/templates/music/index.html
{%if all_alb%}
    <ul>
        {%for al in all_alb%}
        <li>
            <a href="{% url 'music:details' al.id %}">
                {{al.album_title}}
            </a>
        </li>
        {%endfor%}
    </ul>
{%else%}
<h3>"There is no album"</h3>
{%endif%}